### ISSUE TITLE
output

### ISSUE THREAD

**Issue by Raven-233486** [tinygrox/Barotrauma_ChineseFixes#6]
![QQ图片20221021130329](https://user-images.githubusercontent.com/72175577/197279747-d84be1b7-ebe3-4859-9d77-6c22277bb37a.png)
![QQ图片20221021130324](https://user-images.githubusercontent.com/72175577/197279766-ccc733bf-abda-4e35-b9f3-09f558d26e61.png)

**Comment by tinygrox** [comment]
问题未成功复现。请提供更多信息。
---
问题相关
https://github.com/tinygrox/Barotrauma_ChineseFixes/blob/61bb7c7a6dbcdcd1061c7d28226989a433b32a4b/Texts/SimplifiedChineseVanilla.xml#L6524

之前版本已经修正过并已同步更新到创意工坊，请确定订阅是否为最新（目前mod版本更新为1.0.3 最后更新于10月20日），且语言切换到了`中文（简体）[修正]`
如问题已解决，请关闭该 issue。如未能解决，请提供更多信息（包括但不限于提供问题出现时整个屏幕的截图、游戏的语言设置，已安装的mod列表等）。

**Comment by Raven-233486** [comment]
ok
